language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
deploy:
  skip_cleanup: true
  on:
    repo: iamolegga/collection-decorator
    branch: master
  provider: npm
  email: iamolegga@gmail.com
  api_key:
    secure: cU79egog3YuVbH9cVp40qkXpGcOMv+bSZ0Kn9OBPX66q5Z8JpfMpy/xRRZtcHoDSuQviV6jyLmnpeXYlvasAAvf1WVP7xBq8A/6hstz+fbpG5Eckt+mBWINJOeBJUu/inkliTxhZ9jcYuDO10UUc9fX/L4+xCKMVDcUP/5DjkuUql6FxX2goSTpu6EOcHr27t9ERmEatn0Eezdkcd/VFUi2jebLMdgqJlr27e6RTxOgVRDVgbrNMTUrot2/3RxVj/49ubU/Ojv0RiiAwPrRZkWWzdEHMQMdlbjkoSkDS/ak37k1tJhwy6cZWmmsDcmNS/bEhQirWR9XTCoBolxcefM08A7YadC3S/m3V6X4LC9t7xZdt9dN7X/oCv+TTIEwHoFGqwSN9SJil7FcyAoiH9fBZaX5FG805UOpSysxi7q4PvNVvJ8sxKc6z9Xqa8po4bNFz2PXegwdNHyTQ+FyQ6ouFC79sQuWvzykQbWLhimJyrGQHuiB161a5bTh9ppT0K8AiBrph/jt4N/Co4JMLfPBoIhi/oMsqnAdvZIUmdToAotx3A1UB0Ms/BuIL0iygvlgZJsC4qB2YHr8T0PXyxqbNmSn4p2ORwW4MqpdbcoapuXsFwgD7JgjFfS7UdcViCTcfKH6JztL/bnCFkQpo6KXzEnU2I5NjjPE1fcs6aLw=
script:
  - npm run build
  - npm run test
after_deploy:
  - npm run report
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
